fix(bin/dotfiles_bin_fallback/packages/mmdc): install chrome-headless
The mmdc.sh package installed mermaid-cli but not chrome-headless-shell.
This causes mmdc.sh to fail with the following error message:

```
Error: Could not find Chrome (ver. 148.0.7778.97). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome-headless-shell`) or
 2. your cache path is incorrectly configured (which is: /home/lucas_dev/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
```

Update the installation script to install the required
chrome-headless-shell version